version: 0.2
            
phases:
  install:
    runtime-versions:
      python: 3.7
    commands:     
      - python -m venv venv
      - source venv/bin/activate
  build:
    commands:
      - python tests.py
      - export BUCKET=lambda-deployment-artifacts-pipeline-demo
      - aws cloudformation package --template-file template.yml --s3-bucket $BUCKET --output-template-file outputtemplate.yml
artifacts:    
  type: zip
  files:
    - template.yml
    - outputtemplate.yml
