# This is a basic workflow to help you get started with Actions:
name: CICD

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ main ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

        
# Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

       # Runs a set of commands using the runners shell
      - name: Use node js
        user: actions/setup-node@v1
        with:
         node-version: ${{ matrix.node-version }}
      - name: npm install & build
        run: |
          npm install
          npm run build

        env:
          CI: true


deploy:
  needs: [build]
  runs-on: ubuntu-latest

  steps:
   - name: SSH deploy
     uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          curl -fsSL https://deb.nodesource.com/setup_16.x | sudo -E bash -
          apt-get install -y nodejs
          npm install -g npm@latest
          npm install -g pm2
          cd /home/ubuntu/aws-codepipeline-s3-codedeploy-linux
          git pull origin main
          rm -rf node_modules
          npm install
          npm run build
 #        pm2 start npm --name "salt" -- start
